// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250315111126_SeedJobsFix")]
    partial class SeedJobsFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Application", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Server.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FixedSalary")
                        .HasColumnType("int");

                    b.Property<DateTime>("JobPostedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalaryFrom")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryTo")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Description = "Develop and maintain web applications.",
                            JobPostedOn = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Remote",
                            SalaryFrom = 80000,
                            SalaryTo = 120000,
                            category = "IT",
                            country = "USA",
                            title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            City = "Toronto",
                            Description = "Analyze business data and provide insights.",
                            JobPostedOn = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hybrid",
                            SalaryFrom = 60000,
                            SalaryTo = 90000,
                            category = "Analytics",
                            country = "Canada",
                            title = "Data Analyst"
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            Description = "Oversee project timelines and resources.",
                            JobPostedOn = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "On-Site",
                            SalaryFrom = 70000,
                            SalaryTo = 110000,
                            category = "Management",
                            country = "UK",
                            title = "Project Manager"
                        },
                        new
                        {
                            Id = 4,
                            City = "Berlin",
                            Description = "Manage hiring and employee relations.",
                            FixedSalary = 65000,
                            JobPostedOn = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Remote",
                            category = "Human Resources",
                            country = "Germany",
                            title = "HR Specialist"
                        },
                        new
                        {
                            Id = 5,
                            City = "Paris",
                            Description = "Plan and execute marketing campaigns.",
                            JobPostedOn = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hybrid",
                            SalaryFrom = 50000,
                            SalaryTo = 75000,
                            category = "Marketing",
                            country = "France",
                            title = "Marketing Coordinator"
                        },
                        new
                        {
                            Id = 6,
                            City = "Amsterdam",
                            Description = "Design user interfaces and experiences.",
                            JobPostedOn = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "On-Site",
                            SalaryFrom = 55000,
                            SalaryTo = 85000,
                            category = "Design",
                            country = "Netherlands",
                            title = "UX Designer"
                        },
                        new
                        {
                            Id = 7,
                            City = "Sydney",
                            Description = "Protect systems and networks from cyber threats.",
                            JobPostedOn = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hybrid",
                            SalaryFrom = 75000,
                            SalaryTo = 100000,
                            category = "Security",
                            country = "Australia",
                            title = "Cybersecurity Analyst"
                        },
                        new
                        {
                            Id = 8,
                            City = "Bangalore",
                            Description = "Manage and optimize databases.",
                            FixedSalary = 72000,
                            JobPostedOn = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Remote",
                            category = "IT",
                            country = "India",
                            title = "Database Administrator"
                        },
                        new
                        {
                            Id = 9,
                            City = "San Francisco",
                            Description = "Evaluate business processes and performance.",
                            JobPostedOn = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "On-Site",
                            SalaryFrom = 65000,
                            SalaryTo = 95000,
                            category = "Business",
                            country = "USA",
                            title = "Business Analyst"
                        },
                        new
                        {
                            Id = 10,
                            City = "Vancouver",
                            Description = "Write and edit content for various platforms.",
                            JobPostedOn = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Remote",
                            SalaryFrom = 45000,
                            SalaryTo = 70000,
                            category = "Writing",
                            country = "Canada",
                            title = "Content Writer"
                        },
                        new
                        {
                            Id = 11,
                            City = "Munich",
                            Description = "Maintain and troubleshoot network infrastructure.",
                            JobPostedOn = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hybrid",
                            SalaryFrom = 68000,
                            SalaryTo = 105000,
                            category = "Networking",
                            country = "Germany",
                            title = "Network Engineer"
                        },
                        new
                        {
                            Id = 12,
                            City = "Lyon",
                            Description = "Optimize websites for search engines.",
                            FixedSalary = 58000,
                            JobPostedOn = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Remote",
                            category = "Digital Marketing",
                            country = "France",
                            title = "SEO Specialist"
                        },
                        new
                        {
                            Id = 13,
                            City = "Manchester",
                            Description = "Design and implement cloud solutions.",
                            JobPostedOn = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "On-Site",
                            SalaryFrom = 90000,
                            SalaryTo = 130000,
                            category = "Cloud Computing",
                            country = "UK",
                            title = "Cloud Architect"
                        },
                        new
                        {
                            Id = 14,
                            City = "Los Angeles",
                            Description = "Develop AI models and algorithms.",
                            JobPostedOn = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hybrid",
                            SalaryFrom = 100000,
                            SalaryTo = 150000,
                            category = "Artificial Intelligence",
                            country = "USA",
                            title = "AI Engineer"
                        },
                        new
                        {
                            Id = 15,
                            City = "Pune",
                            Description = "Provide technical assistance to customers.",
                            FixedSalary = 50000,
                            JobPostedOn = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Remote",
                            category = "Customer Support",
                            country = "India",
                            title = "Technical Support"
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
